### ISSUE TITLE
Map brain regions from Silleti whole human brain transcriptomics paper to HBA

### ISSUE THREAD

**Issue by dosumis** [obophenotype/provisional_cell_ontology#50]
[supplementary-material](https://www.biorxiv.org/content/10.1101/2022.10.12.511898v1.supplementary-material) - table2

Column: `Top three regions`.  Record location for all regions with > some threshold (say 5%).  Regions should be mapped to DHBA  CURIE - accession part of CURIEs match ID in column 1 of supp mat table 1.

Add comment for all: location based on origins of cells in brain dissections with cut-off of {x}% to account for dissection errors { add percentages here}.

**Comment by hkir-dev** [comment]
Brain regions records added with a configurable 10% threshold:
```
  - annotationProperty: some_soma_located_in
    var: HBA_1
    annotations:
      - annotationProperty: rdfsComment
        text: "%s"
        vars:
          - HBA_1_comment
```
Separate HBA columns used (HBA_1, HBA_2...) because [DOSDP annotation tag](https://github.com/INCATools/dead_simple_owl_design_patterns/blob/master/src/schema/dosdp_schema.yaml#L278) that gets list as parameter is not allowing adding axiom annotations (HBA_1_comment)

```
    <owl:Axiom>
        <owl:annotatedSource rdf:resource="http://purl.obolibrary.org/obo/PCL_0051427"/>
        <owl:annotatedProperty rdf:resource="http://purl.obolibrary.org/obo/PCL_0010063"/>
        <owl:annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/HBA_4008"/>
        <rdfs:comment>Location assignment based on origin of cells in brain dissections with a cut-off of 10% to account for dissection errors Cerebral cortex: 10.0%.</rdfs:comment>
    </owl:Axiom>
```
